### ISSUE TITLE
Add other irc events

### ISSUE THREAD

**Issue by denispasin** [litaio/lita-irc#16]
add an event on quit/part/nickchange

**Comment by simmel** [comment]
Hey @denispasin 
What do you thing about using http://www.rubydoc.info/gems/cinch/file/docs/events.md#leaving instead of quit/part? Does that make sense from a lita perspective?

**Comment by denispasin** [comment]
Yep. Although in IRC protocol it's totally different messages.

**Comment by simmel** [comment]
What do you think @jimmycuadra ?

**Comment by jimmycuadra** [comment]
Sounds good in general. I reviewed the PR.
