### ISSUE TITLE
user_joined_room event doesn't fire

### ISSUE THREAD

**Issue by PDaily** [litaio/lita-irc#17]
Like the title says, this event doesn't fire (at least that I can tell)

Ex.

``` ruby
on :user_joined_room, :user_joined_greet

def user_joined_greet(payload)
  puts "User Joined Room!"
end
```

Renders nothing in the console. Everything else works though.

**Comment by zackp30** [comment]
Getting same thing here.

**Comment by simmel** [comment]
Hm, a bit tad late but I'll look into this as I was the one who contributed it.

What IRC server and version of lita are you using?

**Comment by simmel** [comment]
Haha, I spent way to long to debug this. It's not there because there hasn't been a release the the code was added.
@jimmycuadra needs to do a release! I have a PR incoming to add an `op` method though, so maybe we can wait until I do that PR?

This can be closed.

**Comment by jimmycuadra** [comment]
Remind me after your new PR to release a new gem!
